# Generated by Django 6.0.6 on 2026-06-07 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='adaptive_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exam',
            name='is_template',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exam',
            name='marks_per_question',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='exam',
            name='negative_mark',
            field=models.FloatField(default=0.25),
        ),
        migrations.AddField(
            model_name='exam',
            name='negative_marking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exam',
            name='timer_minutes',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='correct_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='obtained_marks',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='skipped_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='total_marks',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='wrong_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='examattemptanswer',
            name='marks_awarded',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='examquestion',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10),
        ),
    ]
