# Generated by Django 6.0.6 on 2026-06-07 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_exam_adaptive_mode_exam_is_template_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='is_template',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='marks_per_question',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='negative_mark',
        ),
        migrations.RemoveField(
            model_name='examattempt',
            name='obtained_marks',
        ),
        migrations.RemoveField(
            model_name='examattempt',
            name='skipped_count',
        ),
        migrations.RemoveField(
            model_name='examattempt',
            name='total_marks',
        ),
        migrations.RemoveField(
            model_name='examattemptanswer',
            name='marks_awarded',
        ),
        migrations.RemoveField(
            model_name='examquestion',
            name='difficulty',
        ),
        migrations.AlterField(
            model_name='exam',
            name='timer_minutes',
            field=models.IntegerField(default=20),
        ),
        migrations.CreateModel(
            name='ExamAttemptQuestionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.IntegerField()),
                ('question_text', models.TextField()),
                ('correct_answer', models.TextField()),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.examattempt')),
            ],
        ),
    ]
