# Generated by Django 6.0.6 on 2026-06-07 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_remove_exam_is_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='duration_minutes',
            field=models.IntegerField(default=10),
        ),
    ]
