# Generated by Django 6.0.6 on 2026-06-07 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_exam_duration_minutes'),
        ('syllabus', '0002_alter_subtopic_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='examattemptanswer',
            name='answered_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='examattempt',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='exam.exam'),
        ),
        migrations.CreateModel(
            name='ExamSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_questions', models.IntegerField()),
                ('difficulty', models.CharField(max_length=20)),
                ('questions_json', models.JSONField()),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subtopic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='syllabus.subtopic')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syllabus.topic')),
            ],
        ),
    ]
