# Generated by Django 6.0.6 on 2026-06-07 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='subject',
        ),
    ]
