# Generated by Django 6.0.6 on 2026-06-09 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0003_questionbank_questionbankoption'),
        ('syllabus', '0002_alter_subtopic_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='questionbank',
            unique_together={('subtopic', 'question_text')},
        ),
    ]
