# Generated by Django 6.0.6 on 2026-06-06 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtopic',
            name='name',
            field=models.CharField(max_length=400),
        ),
    ]
